"""adding block to users table

Revision ID: 367643f84fe9
Revises: 202bca19d0a3
Create Date: 2020-03-22 08:13:46.336958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367643f84fe9'
down_revision = '202bca19d0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blocked')
    # ### end Alembic commands ###
