"""allowedusers table

Revision ID: 3e9c48cb3dd4
Revises: 714c67a56a6f
Create Date: 2020-03-17 09:02:31.325090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c48cb3dd4'
down_revision = '714c67a56a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_users_email'), 'allowed_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allowed_users_email'), table_name='allowed_users')
    op.drop_table('allowed_users')
    # ### end Alembic commands ###
